image: openpyxl/openpyxl-ci

pipelines:
  default:
  - step:
      caches:
        - pip
      script:
        - /tools/clean-launch.sh tox --skip-missing-interpreters -- -qrf
        - export GIT_ID=$(hg tip --template '{node}\n')
        - export GIT_AUTHOR_NAME=$(hg tip --template '{author|person}\n')
        - export GIT_AUTHOR_EMAIL=$(hg tip --template '{author|email}\n')
        - export GIT_COMMITTER_NAME=$(hg tip --template '{author|person}\n')
        - export GIT_COMMITTER_EMAIL=$(hg tip --template '{author|email}\n')
        - export GIT_MESSAGE=$(hg tip --template '{desc}\n')
        - export GIT_BRANCH=$(hg branch)
        - export GIT_URL=https://bitbucket.org/openpyxl/openpyxl
        - /tools/clean-launch.sh tox -e cov
